[tool.poetry]
name = "restless"
version = "0.1.1"
description = "Ansible interactions"
authors = ["Get-Tony <Get-Tony@outlook.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ansible = "^7.1.0"
lib_standard = { git = "https://github.com/Get-Tony/lib_standard.git", tag = "v1.2.1" }

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.10"
mypy = "^0.991"
black = "^22.12.0"
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pydocstyle = "^6.3.0"
pycodestyle = "^2.10.0"
ipykernel = "^6.20.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
